### ISSUE TITLE
description失效

### ISSUE THREAD

**Issue by jiahao-jayden** [TIANLI0/BF-OK#3]
> 又打扰你了，祝你中秋节快乐

不知道是不是因为主题魔改的BUG，在配置description项的时候，`hexo s`后无法正常显示文章的简介，后来换了`<!--more-->`也无法正常显示

配置如图：
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-09_19-31-26.png)

实际显示：
![](https://cdn.staticaly.com/gh/kjhuanhao/blogcdn@master/img/Snipaste_2022-09-09_19-31-52.png)

**Comment by TIANLI0** [comment]
这个不清楚，你可以更新新版本Butterfly试试，我使用的时候也没有用过description
